receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch: {}

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000?database=openlit
    username: default
    password: ""

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
